version: '2.4'
services:
  api:
    image: api-image
    ports:
      - "5075:8080"
    build:
      context: ./CommLifecycle.Api
      dockerfile: Dockerfile
    entrypoint: ["dotnet", "CommLifecycle.Api.dll"]
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      sql-server:
        condition: service_healthy

  web:
    image: web-image
    environment:
      Okta:OktaDomain: ${OKTA_DOMAIN}
      Okta:ClientId: ${OKTA_CLIENT_ID}
      Okta:ClientSecret: ${OKTA_CLIENT_SECRET}
      Okta:AuthorizationServerId: ${OKTA_AUTHORIZATION_SERVER_ID}
    ports:
      - "8000:8080"
    build:
      context: ./CommLifecycle.Web
      dockerfile: Dockerfile
    entrypoint: ["dotnet", "CommLifecycle.Web.dll"]
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-CU13-ubuntu-20.04
    container_name: sql-server-container
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -C -S localhost -U sa -P ${DB_PASSWORD} -Q \"SELECT 1\" -b -o /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data: