version: '2.4'
services:
  aspnet:
    entrypoint: ["dotnet", "watch", "run", "--urls", "http://*:8080", "--non-interactive"]
    volumes:
      - ./BlazorApp1:/App/BlazorApp1
      - ./SharedModels:/App/SharedModels
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - DOTNET_WATCH_RESTART_ON_RUDE=1
    build:
      target: dev