version: '2.4'
services:
  aspnet:
    image: counter-image
    environment:
      Okta:OktaDomain: ${OKTA_DOMAIN}
      Okta:ClientId: ${OKTA_CLIENT_ID}
      Okta:ClientSecret: ${OKTA_CLIENT_SECRET}
      Okta:AuthorizationServerId: ${OKTA_AUTHORIZATION_SERVER_ID}
      ConnectionStrings:BlazorWebAppContext: "Server=sql-server;Database=MyDb;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True"

    ports:
      - "8000:8080"
    build: .
    depends_on:
      sql-server:
        condition: service_healthy
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-CU13-ubuntu-20.04
    container_name: sql-server-container
    environment:
      SA_PASSWORD: Password1
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -C -S localhost -U sa -P Password1 -Q \"SELECT 1\" -b -o /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data: